add an insert lookup country method
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Program.cs(16,35): error CS7036: There is no argument given that corresponds to the required formal parameter 'abbreviation' of 'LookupCountryData.AddLookupCountry(string, string, string)' [/home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/PokerLeaderboard.Console.csproj]

The build failed. Fix the build errors and run again.

real    0m2.000s
user    0m1.802s
sys     0m0.234s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Unhandled exception. Npgsql.PostgresException (0x80004005): 22001: value too long for type character varying(10)
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at PokerLeaderboard.Infrastructure.LookupCountryData.AddLookupCountry(String connectionString, String fullName, String abbreviation) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/LookupCountryData.cs:line 19
   at PokerLeaderboard.Console.Program.Main(String[] args) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/Program.cs:line 16
  Exception data:
    Severity: ERROR
    SqlState: 22001
    MessageText: value too long for type character varying(10)
    File: varchar.c
    Line: 624
    Routine: varchar

real    0m5.555s
user    0m3.154s
sys     0m0.440s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Unhandled exception. Npgsql.PostgresException (0x80004005): 22001: value too long for type character varying(10)
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at PokerLeaderboard.Infrastructure.LookupCountryData.AddLookupCountry(String connectionString, String fullName, String abbreviation) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/LookupCountryData.cs:line 19
   at PokerLeaderboard.Console.Program.Main(String[] args) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/Program.cs:line 18
  Exception data:
    Severity: ERROR
    SqlState: 22001
    MessageText: value too long for type character varying(10)
    File: varchar.c
    Line: 624
    Routine: varchar

real    0m5.389s
user    0m2.841s
sys     0m0.411s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Country Name: United States of America. Abbreviation: USA.
Country Name: Great Britain. Abbreviation: GBR.
Country Name: 548ed5bd-0113-42a2-808e-21bec459a178. Abbreviation: bec459a178.
Country Name: 1aeff7ea-c4b7-4dd7-b117-d7b502967031. Abbreviation: b502967031.
Country Name: 33774f59-a77b-4bba-ab52-18f20f681cb1. Abbreviation: f20f681cb1.
Country Name: d87d4ff5-f3fa-41e1-a2e2-168d60940179. Abbreviation: 8d60940179.
Country Name: cd0ca105-b89d-4a7d-b47f-d8743f4b0b4f. Abbreviation: 743f4b0b4f.
Country Name: 67921441-9717-468a-bd07-f5e974d0d69e. Abbreviation: e974d0d69e.
Country Name: df31f7ef-8961-4231-9d33-23aae40b4aa7. Abbreviation: aae40b4aa7.
Country Name: cdac164e-2ae8-4474-aaa8-cc34f2ecb7d0. Abbreviation: 34f2ecb7d0.
Country Name: ee86e807-f885-46bd-8233-0b44f6a6d2eb. Abbreviation: 44f6a6d2eb.
Country Name: 11044d78-de20-47f1-9b36-1933510e1de0. Abbreviation: 33510e1de0.
Country Name: 8800afab-643c-424b-9f93-5998169f7d7f. Abbreviation: 98169f7d7f.
Country Name: 5fb3b10e-58b4-4886-b02c-d5c5fd3c3fb7. Abbreviation: c5fd3c3fb7.
Country Name: 3bdeffe3-3c66-49fb-9254-a02bbd2c3e72. Abbreviation: 2bbd2c3e72.
Country Name: 974c0891-5507-4912-89f9-b50e823ed363. Abbreviation: 0e823ed363.
Country Name: ab5cf3a0-f3c3-49d3-95ad-bfa1996d091b. Abbreviation: a1996d091b.
Country Name: 3ac42d31-e75b-4e41-b378-079dad2ea7b4. Abbreviation: 9dad2ea7b4.
Country Name: 952bab86-efd8-413b-ae73-a323130fa8f6. Abbreviation: 23130fa8f6.
Country Name: d0f74c9c-abf8-4370-ae90-6d6f01d286ac. Abbreviation: 6f01d286ac.
Country Name: 6f11bcc2-6c35-4573-91c7-dfd73612e7a4. Abbreviation: d73612e7a4.
Country Name: b97793dc-efee-483b-bd72-9d747662420b. Abbreviation: 747662420b.
Country Name: dc3d28fd-7251-4119-8058-15a8786a984d. Abbreviation: a8786a984d.
Country Name: cf3751ee-40fb-4525-83f9-e4e114068492. Abbreviation: e114068492.
Country Name: aa10c6cf-5e79-473d-8f33-06ae7cec727e. Abbreviation: ae7cec727e.
Country Name: 1880318c-fa8e-4530-9dcd-752929f74d0b. Abbreviation: 2929f74d0b.
Country Name: 57840b72-608e-415c-b6c9-6f24905e849b. Abbreviation: 24905e849b.
Country Name: e5c97676-cb8c-4512-81ad-7e5739a97e22. Abbreviation: 5739a97e22.
Country Name: af0700ce-ba13-482a-bfac-38444e058f66. Abbreviation: 444e058f66.
Country Name: c21b19ce-17df-4f18-bfc3-c8a0870bd0de. Abbreviation: a0870bd0de.
Country Name: e7504e30-7757-450c-b030-b940671fbcb9. Abbreviation: 40671fbcb9.
Country Name: 1280fddf-4643-46fe-88b9-ce08f29d4d5b. Abbreviation: 08f29d4d5b.
Country Name: e8187821-1572-4c0d-b4b6-4234a80a8c09. Abbreviation: 34a80a8c09.
Country Name: ada40e55-8219-4146-95bf-033fc558c261. Abbreviation: 3fc558c261.
Country Name: 0b20a069-ce63-4497-85fe-6434199be4c4. Abbreviation: 34199be4c4.
Country Name: ff5761eb-408e-4021-812c-d1089ad17cfb. Abbreviation: 089ad17cfb.
Country Name: 92f030c2-18f6-485b-a2c5-9604af3c0803. Abbreviation: 04af3c0803.
Country Name: 2c3c8b59-aa92-4940-b1ff-ea93d77cca66. Abbreviation: 93d77cca66.
Country Name: 1f55f08b-ccc1-4227-8999-1ced1fd02f4a. Abbreviation: ed1fd02f4a.
Country Name: 7d08b55e-bd38-42b1-a249-4b1800ea13b5. Abbreviation: 1800ea13b5.
Country Name: c0772796-d560-4bf4-8b99-9e6d526c4210. Abbreviation: 6d526c4210.
Country Name: 866b15ca-a2aa-4955-bc35-7132c3b15479. Abbreviation: 32c3b15479.
Country Name: 378db9bb-e0e1-4d37-a76c-d944b6d84e63. Abbreviation: 44b6d84e63.
Country Name: 8bde1df9-9b30-410c-b71c-ca2cd373249a. Abbreviation: 2cd373249a.
Country Name: e197bc3c-6d12-44e4-95dd-be5207b21fb9. Abbreviation: 5207b21fb9.
Country Name: 7112b579-822d-4378-a851-5a2b515d8e10. Abbreviation: 2b515d8e10.
Country Name: 54a8a94c-6fda-42cc-8c02-ab5fe49d8a53. Abbreviation: 5fe49d8a53.
Country Name: 8a92242f-12a0-421b-925e-3b1bbaae3596. Abbreviation: 1bbaae3596.
Country Name: 954fcaf3-46ee-4ba8-8bb2-5ad2b78d43ac. Abbreviation: d2b78d43ac.
Country Name: 47c76426-dc8d-46a5-9ff9-3b55352d40e6. Abbreviation: 55352d40e6.
Country Name: 2cebafe3-a42b-4fdf-b1de-1f996d35fb1e. Abbreviation: 996d35fb1e.
Country Name: 14f361d0-afd8-437e-8133-cb4366e4b1d0. Abbreviation: 4366e4b1d0.
Country Name: 550ceb3c-3289-4ac8-9e61-66bfab586272. Abbreviation: bfab586272.
Country Name: 98d5410d-e40a-4bc2-b079-4a81f0a2e609. Abbreviation: 81f0a2e609.
Country Name: e7418e7a-f143-405b-8e55-17eafd3e88be. Abbreviation: eafd3e88be.
Country Name: 19082159-ec59-4c02-8da5-4653f1baa412. Abbreviation: 53f1baa412.
Country Name: 4e8bd780-a088-43f5-9c17-9ddd3ab109c3. Abbreviation: dd3ab109c3.
Country Name: ee61a0ee-7fb4-4197-b844-5936b23237e2. Abbreviation: 36b23237e2.
Country Name: c425f40f-8b4b-4358-b9ab-94d533468394. Abbreviation: d533468394.
Country Name: 9ffff3e9-f11c-4d56-a67e-0a65b3c85af6. Abbreviation: 65b3c85af6.
Country Name: d005a9d8-4c71-459e-8939-c3d3dd4a1b83. Abbreviation: d3dd4a1b83.
Country Name: 9fca1cff-f3df-4251-9b47-bb96f1d1cf08. Abbreviation: 96f1d1cf08.
Country Name: 77e323e6-95f9-4c3b-9562-e30c4fc42c3a. Abbreviation: 0c4fc42c3a.
Country Name: 22becd8d-cdba-41c2-98c6-742445ac555c. Abbreviation: 2445ac555c.
Country Name: 3649e8bb-504e-467f-8277-93634ccaa58a. Abbreviation: 634ccaa58a.
Country Name: add2b0e4-c449-4987-baa4-efb69b74fc7d. Abbreviation: b69b74fc7d.
Country Name: 7cedea68-c08a-49d9-a052-812d59a50ca8. Abbreviation: 2d59a50ca8.
Country Name: c318a398-c788-4c61-a536-4d481ddde8de. Abbreviation: 481ddde8de.
Country Name: b01e00c3-b585-4c64-9bd2-9993b9576987. Abbreviation: 93b9576987.
Country Name: f58be859-76b7-4968-bdf2-3ef8c54ece1f. Abbreviation: f8c54ece1f.
Country Name: cb04e99c-55e7-4d27-a800-fe6bc0ffb693. Abbreviation: 6bc0ffb693.
Country Name: 086e62ec-acbd-4829-af2f-dcc8e8fbbdee. Abbreviation: c8e8fbbdee.
Country Name: 0b6ab069-ece2-4cb7-b9e7-a7f650779488. Abbreviation: f650779488.
Country Name: f0462b23-b247-45be-b73f-32ebb2da9abf. Abbreviation: ebb2da9abf.
Country Name: 460f96af-a172-4a95-b59b-bd51c9073dda. Abbreviation: 51c9073dda.
Country Name: 2b848475-f4af-4e12-8e2e-7cfe1a05ee7a. Abbreviation: fe1a05ee7a.
Country Name: 37e2da57-dc76-484d-882e-b0a54b316347. Abbreviation: a54b316347.
Country Name: 06a1b2d2-d1bb-45f0-b10b-21c71d68b4e8. Abbreviation: c71d68b4e8.
Country Name: 7592585f-7834-4220-8ecc-a636b370a056. Abbreviation: 36b370a056.
Country Name: 328d2d21-54f9-4713-a68f-aff0520cb8fc. Abbreviation: f0520cb8fc.
Country Name: a6b91181-4cac-442f-95c4-099e147b9317. Abbreviation: 9e147b9317.
Country Name: c71d44df-7690-4259-9731-1ecbf6e29f10. Abbreviation: cbf6e29f10.
Country Name: 0bfc58c9-34c7-4f4f-8d3a-9e91d3b7f823. Abbreviation: 91d3b7f823.
Country Name: b7e760a9-1a32-4ad3-81ec-d7ad77c7f3c3. Abbreviation: ad77c7f3c3.
Country Name: e35ea9aa-311f-4bff-bbda-85c01e2a75ad. Abbreviation: c01e2a75ad.
Country Name: 4ab338f5-f29a-461b-925c-4157a21499d5. Abbreviation: 57a21499d5.
Country Name: 7d332c76-c86d-4f5a-9e73-e847c8243841. Abbreviation: 47c8243841.
Country Name: 2ec84f27-1823-4825-adea-4d744941f323. Abbreviation: 744941f323.
Country Name: 405a9cc5-1091-4edf-928a-4faaf17c549e. Abbreviation: aaf17c549e.
Country Name: 85af6711-9998-4963-87ba-55976eb02278. Abbreviation: 976eb02278.
Country Name: c0b350b9-04e9-4c4a-b31f-5064b999f3ba. Abbreviation: 64b999f3ba.
Country Name: 653a7ea2-ca35-47c1-9bfd-7d76de4bbb0f. Abbreviation: 76de4bbb0f.
Country Name: ca6c5cf9-fa74-43cf-942b-f943b9ba61f6. Abbreviation: 43b9ba61f6.
Country Name: 7b9fd244-556e-41e2-9abd-b3c59fadca04. Abbreviation: c59fadca04.
Country Name: f8251281-524b-4cf1-bfd2-d1dfaeda583f. Abbreviation: dfaeda583f.
Country Name: 6b5b3997-52a4-44df-8fe7-776084826c3b. Abbreviation: 6084826c3b.
Country Name: e2cbee57-17a4-4cc9-803c-8bc2506a36fd. Abbreviation: c2506a36fd.
Country Name: 179b3f6a-fdee-460e-b1ed-a36a7030f011. Abbreviation: 6a7030f011.
Country Name: a48c0729-0c3e-4530-9d9c-ca0456475395. Abbreviation: 0456475395.
Country Name: e800a477-064b-44ed-a6cb-5c17bcef365f. Abbreviation: 17bcef365f.
Country Name: f10e1fe0-e18d-4a8f-93e8-25a5406cb6f9. Abbreviation: a5406cb6f9.
Country Name: d95a7361-2a8c-40af-b2ae-b99bd0d8c4e6. Abbreviation: 9bd0d8c4e6.

real    1m39.921s
user    0m3.207s
sys     0m0.312s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$