add a new class to do look up country
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ cd PokerLeaderboard.Console/
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ dotnet --help
.NET Core SDK (3.1.108)
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET Core application.

runtime-options:
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.
  --additional-deps <path>         Path to additional deps.json file.
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --roll-forward <setting>         Roll forward to framework version  (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable).

path-to-application:
  The path to an application .dll file to execute.

Usage: dotnet [sdk-options] [command] [command-options] [arguments]

Execute a .NET Core SDK command.

sdk-options:
  -d|--diagnostics  Enable diagnostic output.
  -h|--help         Show command line help.
  --info            Display .NET Core information.
  --list-runtimes   Display the installed runtimes.
  --list-sdks       Display the installed SDKs.
  --version         Display .NET Core SDK version in use.

SDK commands:
  add               Add a package or reference to a .NET project.
  build             Build a .NET project.
  build-server      Interact with servers started by a build.
  clean             Clean build outputs of a .NET project.
  help              Show command line help.
  list              List project references of a .NET project.
  msbuild           Run Microsoft Build Engine (MSBuild) commands.
  new               Create a new .NET project or file.
  nuget             Provides additional NuGet commands.
  pack              Create a NuGet package.
  publish           Publish a .NET project for deployment.
  remove            Remove a package or reference from a .NET project.
  restore           Restore dependencies specified in a .NET project.
  run               Build and run a .NET project output.
  sln               Modify Visual Studio solution files.
  store             Store the specified assemblies in the runtime package store.
  test              Run unit tests using the test runner specified in a .NET project.
  tool              Install or manage tools that extend the .NET experience.
  vstest            Run Microsoft Test Engine (VSTest) commands.

Additional commands from bundled tools:
  dev-certs         Create and manage development certificates.
  fsi               Start F# Interactive / execute F# scripts.
  sql-cache         SQL Server cache command-line tools.
  user-secrets      Manage development user secrets.
  watch             Start a file watcher that runs a command when files change.

Run 'dotnet [command] --help' for more information on a command.
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ dotnet add ../PokerLeaderboard.Infrastructure/PokerLeaderboard.Infrastructure.csproj
Required command was not provided.
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.

Commands:
  package <PACKAGE_NAME>     Add a NuGet package reference to the project.
  reference <PROJECT_PATH>   Add a project-to-project reference to the project.
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ dotnet add --help
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.

Commands:
  package <PACKAGE_NAME>     Add a NuGet package reference to the project.
  reference <PROJECT_PATH>   Add a project-to-project reference to the project.
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ dotnet add --reference ../PokerLeaderboard.Infrastructure/PokerLeaderboard.Infrastructure.csproj
Required command was not provided.
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.

Commands:
  package <PACKAGE_NAME>     Add a NuGet package reference to the project.
  reference <PROJECT_PATH>   Add a project-to-project reference to the project.
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ dotnet add --reference ../PokerLeaderboard.Infrastructure/PokerLeaderboard.Infrastructure.csproj  .
Required command was not provided.
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.

Commands:
  package <PACKAGE_NAME>     Add a NuGet package reference to the project.
  reference <PROJECT_PATH>   Add a project-to-project reference to the project.
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ dotnet add --reference=../PokerLeaderboard.Infrastructure/PokerLeaderboard.Infrastructure.csproj
Required command was not provided.
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.

Commands:
  package <PACKAGE_NAME>     Add a NuGet package reference to the project.
  reference <PROJECT_PATH>   Add a project-to-project reference to the project.
[kushal@ideapadflex-kushal PokerLeaderboard.Console]$ cd ..
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet add PokerLeaderboard.Console/PokerLeaderboard.Console.csproj reference PokerLeaderboard.Infrastructure/PokerLeaderboard.Infrastructure.csproj
Reference `..\PokerLeaderboard.Infrastructure\PokerLeaderboard.Infrastructure.csproj` added to the project.

real    0m0.646s
user    0m0.604s
sys     0m0.069s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ dotnet buildMicrosoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 34.56 ms for /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.WebAPI/PokerLeaderboard.WebAPI.csproj.
  Restore completed in 42.33 ms for /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/PokerLeaderboard.Infrastructure.csproj.
  Restore completed in 70.1 ms for /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Tests/PokerLeaderboard.Tests.csproj.
  Restore completed in 181.36 ms for /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/PokerLeaderboard.Console.csproj.
  Restore completed in 180.32 ms for /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.BusinessLogic/PokerLeaderboard.BusinessLogic.csproj.
  PokerLeaderboard.Infrastructure -> /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/bin/Debug/netstandard2.1/PokerLeaderboard.Infrastructure.dll
  PokerLeaderboard.BusinessLogic -> /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.BusinessLogic/bin/Debug/netstandard2.1/PokerLeaderboard.BusinessLogic.dll
  PokerLeaderboard.Tests -> /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Tests/bin/Debug/netcoreapp3.1/PokerLeaderboard.Tests.dll
  PokerLeaderboard.WebAPI -> /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.WebAPI/bin/Debug/netcoreapp3.1/PokerLeaderboard.WebAPI.dll
  PokerLeaderboard.Console -> /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/bin/Debug/netcoreapp3.1/PokerLeaderboard.Console.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.28
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Program.cs(10,21): error CS1061: 'Class1' does not contain a definition for 'Print' and no accessible extension method 'Print' accepting a first argument of type 'Class1' could be found (are you missing a using directive or an assembly reference?) [/home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/PokerLeaderboard.Console.csproj]

The build failed. Fix the build errors and run again.
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Unhandled exception. Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "lookup_country_full_name_key"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at PokerLeaderboard.Infrastructure.Class1.Print(String connectionString) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/Class1.cs:line 21
   at PokerLeaderboard.Console.Program.Main(String[] args) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/Program.cs:line 10
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "lookup_country_full_name_key"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: lookup_country
    ConstraintName: lookup_country_full_name_key
    File: nbtinsert.c
    Line: 534
    Routine: _bt_check_unique
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Unhandled exception. Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "lookup_country_full_name_key"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at PokerLeaderboard.Infrastructure.Class1.Print(String connectionString) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/Class1.cs:line 21
   at PokerLeaderboard.Console.Program.Main(String[] args) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/Program.cs:line 10
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "lookup_country_full_name_key"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: public
    TableName: lookup_country
    ConstraintName: lookup_country_full_name_key
    File: nbtinsert.c
    Line: 534
    Routine: _bt_check_unique
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
United States of America
Great Britain
Nepal

real    0m11.658s
user    0m3.363s
sys     0m0.400s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
United States of America
Great Britain
Nepal

real    0m6.054s
user    0m3.649s
sys     0m0.370s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Unhandled exception. System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue) in /_/src/Common/src/System/Data/Common/DbConnectionOptions.Common.cs:line 358
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey) in /_/src/Common/src/System/Data/Common/DbConnectionOptions.Common.cs:line 560
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules) in /_/src/System.Data.Common/src/System/Data/Common/DbConnectionOptions.cs:line 46
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value) in /_/src/System.Data.Common/src/System/Data/Common/DbConnectionStringBuilder.cs:line 155
   at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
   at Npgsql.NpgsqlConnection.GetPoolAndSettings()
   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection..ctor(String connectionString)
   at PokerLeaderboard.Infrastructure.Class1.Print(String connectionString) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/Class1.cs:line 13
   at PokerLeaderboard.Console.Program.Main(String[] args) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/Program.cs:line 10

real    0m3.166s
user    0m2.792s
sys     0m0.466s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
United States of America
Great Britain
Nepal

real    0m9.051s
user    0m3.400s
sys     0m0.324s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Program.cs(9,20): warning CS0219: The variable 'connectionString' is assigned but its value is never used [/home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/PokerLeaderboard.Console.csproj]
Unhandled exception. System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue) in /_/src/Common/src/System/Data/Common/DbConnectionOptions.Common.cs:line 358
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey) in /_/src/Common/src/System/Data/Common/DbConnectionOptions.Common.cs:line 560
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules) in /_/src/System.Data.Common/src/System/Data/Common/DbConnectionOptions.cs:line 46
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value) in /_/src/System.Data.Common/src/System/Data/Common/DbConnectionStringBuilder.cs:line 155
   at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
   at Npgsql.NpgsqlConnection.GetPoolAndSettings()
   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection..ctor(String connectionString)
   at PokerLeaderboard.Infrastructure.Class1.Print(String connectionString) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Infrastructure/Class1.cs:line 13
   at PokerLeaderboard.Console.Program.Main(String[] args) in /home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/Program.cs:line 12

real    0m3.125s
user    0m2.897s
sys     0m0.415s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
United States of America
Great Britain
Nepal

real    0m21.457s
user    0m3.504s
sys     0m0.361s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
Program.cs(12,13): error CS0246: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?) [/home/kushal/src/html/fourwinds/PokerLeaderboardBackend/PokerLeaderboard.Console/PokerLeaderboard.Console.csproj]

The build failed. Fix the build errors and run again.

real    0m2.194s
user    0m2.208s
sys     0m0.266s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$ time dotnet run --project PokerLeaderboard.Console/PokerLeaderboard.Console.csproj
United States of America
Great Britain
Nepal

real    0m5.531s
user    0m3.569s
sys     0m0.347s
[kushal@ideapadflex-kushal PokerLeaderboardBackend]$